package agent

import (
	"context"
)

// LLMChunk is a structured chunk returned by LLM stream.
type LLMChunk struct {
	Thinking         string           `json:"thinking,omitempty"`
	Content          string           `json:"content,omitempty"`
	Reasoning        string           `json:"reasoning,omitempty"`
	ReasoningDetails []map[string]any `json:"reasoning_details,omitempty"`
	ToolCalls        []ToolCall       `json:"tool_calls,omitempty"`
	UsageTokens      int              `json:"usage_tokens,omitempty"`
}

// ToolCall represents a function call generated by the LLM.
type ToolCall struct {
	ID       string           `json:"id"`
	Type     string           `json:"type"`
	Function ToolCallFunction `json:"function"`
}

// ToolCallFunction is the payload containing name and JSON arguments.
type ToolCallFunction struct {
	Name      string `json:"name"`
	Arguments string `json:"arguments"`
}

// LLMClient is the interface for chat models supporting tool calls.
type LLMClient interface {
	Chat(ctx context.Context, model string, messages []map[string]any, tools []ToolDefinition) (<-chan LLMChunk, error)
	ListModels(ctx context.Context) ([]string, error)
}
